### ISSUE TITLE
example from README throws error

### ISSUE THREAD

**Issue by Crghilardi** [Deltares/PointCloudRasterizers.jl#1]
I copied pasted the README today and am getting some kind of name collision issue on Julia 1.2

`julia> index = index(pointcloud, cellsizes)
[ Info: Indexing into a grid of (5000, 5000)
Building raster index..100%|████████████████████████████████████████████████████████████████████████████| Time: 0:00:00
ERROR: cannot assign a value to variable PointCloudRasterizers.index from module Main
Stacktrace:
 [1] top-level scope at REPL[13]:1`

I got around it by changing the name: 
```
julia> inx = index(pointcloud, cellsizes)
[ Info: Indexing into a grid of (5000, 5000)
Building raster index..100%|████████████████████████████████████████████████████████████████████████████| Time: 0:00:00
PointCloudRasterizers.PointCloudIndex(LazDataset of /home/crgxcf/.julia/packages/LazIO/IC3Cp/src/../test/libLAS_1.2.laz with 497536 points.
, 5000x5000x1 Array{Int64,3} with AffineMap([1.0 0.0; 0.0 1.0], [1.44e6, 375000.03]) and WKT , [134, 125, 115, 5105, 5095, 5086, 5076, 10067, 10057, 10047  …  39969, 44980, 44990, 14990, 14980, 9969, 9958, 4948, 4937, 4927])
```

**Comment by visr** [comment]
Hmm it's never a good idea to have a variable use the same name as the function. Thanks for letting us know, it's changed now.
