### ISSUE TITLE
use with LasIO vs LazIO

### ISSUE THREAD

**Issue by Crghilardi** [Deltares/PointCloudRasterizers.jl#3]
Is it possible to use the rasterize a `.las` file read in directly using `LasIO`?

**Comment by evetion** [comment]
At the moment no. One of the things planned is to remove the hardcoded LazIO dataset iteration. This is difficult however, as you still need the header for scaling.

At the moment it is possible however to load `.las`files with `LazIO`.

**Comment by evetion** [comment]
Other packages supporting GeoInterface.x and GeoInterface.y as a MultiPoint geometry are now supported. While LasIO doesn't, it easily could, and we should make sure other new packages in the ecosystem implement GeoInterface.
