### ISSUE TITLE
consolidate bounding box functions?

### ISSUE THREAD

**Issue by Crghilardi** [Deltares/PointCloudRasterizers.jl#7]
Minor note, I think there is some repeated code for the various bounding box and scaling functions.

`scaled_bbox` is defined in `utils.jl` but doesn't seem to get used. `scaled_bbox` gets manually calculated and then used as a tuple variable in `index()`.
The functions in `utils.jl` return a `MVector` but tuples are used in `index`.

1. Should a bounding box return a tuple or `MVector`?
2. Does it make sense to move bounding box/scaling functions out to `LazIO`? I remember we added `bbox` to `LasIO` a while ago.

**Comment by visr** [comment]
Yeah it would be good to straighten this out a bit.

1. Tuple or MVector still requires us to remember and be consistent in the ordering. In the LasIO PR you made we therefore ended up using a NamedTuple. Would that be a good choice for you?
2. Yeah I think so. And LazIO depends on LasIO to could also reuse functions from it if needed.

**Comment by evetion** [comment]
I've used a `NamedTuple` over at GeoArrays to define bounding boxes for cells: https://github.com/evetion/GeoArrays.jl/blob/master/src/geoutils.jl#L59

```julia
bbox = (min_x=0, max_x=1, min_y=0, max_y=1)
```

**Comment by visr** [comment]
Ha, in LasIO this is the NamedTuple:

```
(xmin = 1.44e6, ymin = 375000.03, zmin = 832.1800000000001,
    xmax = 1.44499996e6, ymax = 379999.99, zmax = 972.6700000000001)
```

Do you want to hear my plea on the merits of `xmax` in favor of `max_x`? ;)

**Comment by Crghilardi** [comment]
NamedTuple sounds fine to me. I just wanted to make sure I wasn't missing some high perfomance reason for the `MVector`

Just let me know whatever naming convention we want to standardize on. I can submit something to fix `LasIO` if needed?

My nitpick request:
Can we name them `unscaled_bbox` and `scaled_bbox` instead of just `bbox` and `scaled_bbox`? I don't know if there is something in that JSON standard I missed but I like having both explicit for some reason....

**Comment by evetion** [comment]
> Do you want to hear my plea on the merits of `xmax` in favor of `max_x`? ;)

This calls for a flamewar. What about `x_max`? 👍

I'm open to renaming the bboxes, although it really needs some good documentation then. I remember being confused myself when I encountered the code after a while. Is unscaled before or after scaling? Both have merit.

**Comment by visr** [comment]
> This calls for a flamewar. What about x_max? 👍

:fire: Why break two packages when when you can break one? I suggested using `xmax` [here](https://github.com/visr/LasIO.jl/pull/22#issuecomment-498598552) due to less typing and following GDAL and [PDAL](https://pdal.io/stages/filters.crop.html#options) conventions.

**Comment by Crghilardi** [comment]
FWIW I checked and it looks like [LasTools](https://github.com/LAStools/LAStools/blob/a6ba07ffdd31e492aaf949bb85fe6a2eca2766a0/LASlib/src/lasreader_asc.cpp#L230) uses `max_x` syntax? Although they use `max x y z` when [printing](https://rapidlasso.com/2016/01/10/create-proper-las-1-4-files-with-lastools-for-free/)

I checked and can't find any consistent paradigm for bounding box naming, so I vote for my idea obviously....

I will leave it to you guys to debate and tell me what to type.

**Comment by evetion** [comment]
A nested variant that will enable multidimensional data, without hardcoding dimensions.
🔥 `bbox = (min=(x=0, y=1), max=(x=1, y=1))`

**Comment by visr** [comment]
Ha well I think @Crghilardi just wants to get on with it, so @evetion will you pick something? Nested seems nice, just hope it won't be harder on the compiler.

In any case we are not talking about a specific struct like https://github.com/FugroRoames/RoamesGeometry.jl/blob/af52a35c951bb8e71b363704ed624e117738c850/src/BoundingBox.jl here, just a simple NamedTuple.

**Comment by Crghilardi** [comment]
Also, what would be a good way to ensure consistency in the returned values rather than mixing regular and scientific notation? Wrap everything in `sprint`?

EDIT: after reading forum posts, it sounds more [difficult](https://discourse.julialang.org/t/overriding-show/16315) than I imagined... Probably not worth it

```julia
julia> boundingbox(header2)
(xmin = 488040.5518505732, ymin = 5.189192943947013e6, zmin = 312.945, xmax = 488303.16685057327, ymax = 5.189373150947013e6, zmax = 395.824)
```

**Comment by evetion** [comment]
Fixed in https://github.com/evetion/LazIO.jl/commit/72d437bcea7e43f2f378c1827d24244659409396. Should be registred soon over at https://github.com/JuliaRegistries/General/pull/8110.

Flamewar was fun, settled for the LasIO way. :fire_engine:
